language: python

python:
  - "3.4"
  - "3.5"

sudo: false

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install:
  - apt-get install cmake
  - pip install cffi # pygit doesn't install cffi automatically
  - "./.travis.sh"

install:
  - pip install .

script: python test.py